name: Set up Linux environment
description: Set up everything needed to build and release things on Linux
runs:
  using: composite
  steps:
    - name: Configure git
      run: |
        git config --global user.name "Frida Developers"
        git config --global user.email "oleavr@frida.re"
        git config --global --add safe.directory $GITHUB_WORKSPACE
      shell: bash
    - name: Clean repos
      run: |
        git fetch origin --prune --prune-tags
        git submodule foreach "git clean -ffdx"
        git submodule foreach "git reset --hard HEAD"
        git submodule foreach "git fetch origin --prune --prune-tags"
      shell: bash
    - name: Check out releng/meson
      run: |
        git submodule init -- releng/meson
        git submodule update --depth 1 -- releng/meson
      shell: bash
    - name: Set Frida environment variables
      run: |
        (
          echo "FRIDA=$GITHUB_WORKSPACE"
          echo "FRIDA_VERSION=$(releng/frida_version.py)"
        ) >> $GITHUB_ENV
      shell: bash
